/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    FileView: typeof import('./src/components/FileView.vue')['default']
    MarkerView: typeof import('./src/components/MarkerView.vue')['default']
    PracticeListView: typeof import('./src/components/PracticeListView.vue')['default']
    WaveformView: typeof import('./src/components/WaveformView.vue')['default']
  }
}
